# Generated by Django 4.2.20 on 2025-05-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="location", name="coordinates",),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
