# Generated by Django 4.2.20 on 2025-05-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_remove_location_coordinates_location_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="location", name="address",),
    ]
