# Generated by Django 4.2.20 on 2025-05-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_remove_location_address"),
    ]

    operations = [
        migrations.RemoveField(model_name="journalentry", name="visibility",),
    ]
