# Generated by Django 4.2.20 on 2025-05-11 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_remove_journalentry_visibility"),
    ]

    operations = [
        migrations.RemoveField(model_name="location", name="description",),
    ]
